### ISSUE TITLE
Exit Pages not loaded

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#558]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.6.6 or higher

**PHP Version**: 7.2 FPM

**Webserver**: Apache

**Browser**: Chrome 80

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  
Exit pages resulset is not loaded.

**How to reproduce**  
Open exit pages.

![image](https://user-images.githubusercontent.com/7676540/79842565-4b13d200-83b9-11ea-985c-4e18aa61ef6f.png)

**Additional context**  
The resultset request shows the following error
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getName() on null in /owa/modules/base/classes/resultSetManager.php:1675
Stack trace:
#0 /owa/modules/base/classes/resultSetManager.php(1414): owa_resultSetManager-&gt;getAllRelatedDimensions(NULL)
#1 /owa/modules/base/module.php(2725): owa_resultSetManager-&gt;getResults()
#2 /owa/owa_coreAPI.php(564): owa_baseModule-&gt;getResultSet('visits,pagesPer...', 'exitPagePath,ex...', '6c15f2ff0250d27...', '', 'visits-', '30', '', '', 'last_seven_days', '', '', '', '', 'json', '')
#3 /owa/modules/base/apiRequest.php(86): owa_coreAPI::executeApiCommand(Array)
#4 /owa/modules/base/apiRequest.php(69): owa_apiRequestController-&gt;action()
#5/owa/owa_coreAPI.php(790): owa_apiRequestController-&gt;doAction()
#6  in <b>/owa/modules/base/classes/resultSetManager.php</b> on line <b>1675</b><br />
```

**Comment by Maaiins** [comment]
Some more debug informations
```
19:58:46 2020-04-24 404 [debug_log] pre-reduce set of entities to choose from: Array
(
    [uniqueVisitors] => Array
        (
            [0] => base.session
            [1] => base.request
            [2] => base.action_fact
            [3] => base.domstream
            [4] => base.click
            [5] => base.commerce_transaction_fact
            [6] => base.commerce_line_item_fact
        )

    [visits] => Array
        (
            [0] => base.session
            [1] => base.request
        )

    [bounces] => Array
        (
            [0] => base.session
        )

    [visitDuration] => Array
        (
            [0] => base.session
        )

    [pageViews] => Array
        (
            [0] => base.request
            [1] => base.session
        )

)
 
19:58:46 2020-04-24 404 [debug_log] post-reduce set of entities to choose from: Array
(
    [1] => base.session
)
 
19:58:46 2020-04-24 404 [debug_log] Entities summary levels: Array
(
    [base.session] => 1
)
 
19:58:46 2020-04-24 404 [debug_log] Dimensions: Array
(
    [0] => exitPagePath
    [1] => exitPageUrl
    [2] => exitPageTitle
)
 
19:58:46 2020-04-24 404 [debug_log] Checking the following dimensions for relation to base.session: Array
(
    [0] => exitPagePath
    [1] => exitPageUrl
    [2] => exitPageTitle
    [3] => date
)
 
19:58:46 2020-04-24 404 [debug_log] Could not find a foreign key for exitPagePath in base.session 
19:58:46 2020-04-24 404 [debug_log] exitPagePath is not related to base.session. Moving on to next entity... 
19:58:46 2020-04-24 404 [debug_log] illegal dimension combination: exitPagePath 
19:58:46 2020-04-24 404 [debug_log] Call to a member function getName() on null // #0 /owa/modules/base/classes/resultSetManager.php(1414): owa_resultSetManager->getAllRelatedDimensions(NULL)
#1 /owa/modules/base/controllers/reportsRestController.php(193): owa_resultSetManager->getResults()
#2 /owa/modules/base/controllers/reportsRestController.php(87): owa_reportsRestController->getResultSet()
#3 /owa/owa_controller.php(279): owa_reportsRestController->action()
#4 /owa/owa_coreAPI.php(817): owa_controller->doAction()
#5 /owa/owa_coreAPI.php(1258): owa_coreAPI::runController(Object(owa_reportsRestController))
#6 /owa/owa_caller.php(218): owa_coreAPI::handleRequest(NULL, 'reports')
#7 /owa/api/index.php(46): owa_caller->handleRequest()
#8 {main} 
```

**Comment by padams** [comment]
This is due ot missing foreign key declarations in base.session for those columns. I'll push a fix now.

**Comment by Maaiins** [comment]
Will close this
