### ISSUE TITLE
Transaction view not working

### ISSUE THREAD

**Issue by petsoukos** [Open-Web-Analytics/Open-Web-Analytics#767]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.1

**PHP Version**: 7.4.3 FPM

**Webserver**: Nginx 1.18.0 (Ubuntu)

**Browser**: Any

**Installation Type**

- [x] Standalone

**Description**  
Trying to view transactions details causes a 500 error.
```
2021/07/09 08:53:11 [error] 5588#5588: *965 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method owa_reportsRestController::report_transaction() in /var/www/html/owa/modules/base/controllers/reportsRestController.php:119
Stack trace:
#0 /var/www/html/owa/modules/base/controllers/reportsRestController.php(89): owa_reportsRestController->getReport()
#1 /var/www/html/owa/owa_controller.php(280): owa_reportsRestController->action()
#2 /var/www/html/owa/owa_coreAPI.php(846): owa_controller->doAction()
#3 /var/www/html/owa/owa_coreAPI.php(552): owa_coreAPI::runController()
#4 /var/www/html/owa/modules/base/reportTransactionDetail.php(47): owa_coreAPI::executeApiCommand()
#5 /var/www/html/owa/owa_controller.php(280): owa_reportTransactionDetailController->action()
#6 /var/www/html/owa/owa_coreAPI.php(846): owa_controller->doAction()
#7 /var/www/html/owa/owa_coreAPI.php(833): owa_coreAPI::runController()
#8 /var/www/html/owa/owa_coreAPI.php(1350): owa_coreAPI::performAction()
#9 /var/www/html/owa/owa_caller.php(214): owa_coreAPI:" while reading response header from upstream, client: *.*.*.*, server: example.com, request: "GET /owa/index.php?owa_siteId=b6491f5b72d2ac77f425c26e83808f14&owa_period=last_seven_days&owa_do=base.reportTransactionDetail&owa_transactionId=67401 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "example.com", referrer: "https://example.com/owa/index.php?owa_siteId=b6491f5b72d2ac77f425c26e83808f14&owa_period=last_seven_days&owa_do=base.reportTransactions"
```

**How to reproduce**  
On Ecommerce -> transactions, below the Transaction Roster table, click on any transaction id on the list

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
closing as this was merged.
