### ISSUE TITLE
Problems with REST API

### ISSUE THREAD

**Issue by bclark288** [Open-Web-Analytics/Open-Web-Analytics#780]
**Description**  

I'm getting a 500 error when I try to access the REST api.  I'm using the same parameters as the example in the documentation.  Here is my code:
var urlstring = 'https://owa.tliveinc.com/?owa_apiKey=b6b9c9b9016d2b8b3b9b52e67eba06a3'
                     + '&owa_module=base'
                     + '&owa_version=v1'
                     + '&owa_do=reports'
                     + '&owa_metrics=visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews'
                     + '&owa_dimensions=date,browserType'
                     + '&owa_constraints=browserType%3d%3dFirefox%203.5' 
                     + '&owa_startDate=20100312'
                     + '&owa_endDate=20100331'
                     + '&owa_limit=10'
                     + '&owa_siteId=xxxxxxx6cf9fbfa7f03a8ddf6a5f6c'  //replaced actual site-id here
        xhr.open('GET', urlstring , true);
The stack trace from the Heroku logs is:
2021-08-29T14:29:23.355952+00:00 app[web.1]: Stack trace:
2021-08-29T14:29:23.356056+00:00 app[web.1]: #0 /app/owa_coreAPI.php(379): owa_lib::factory()
2021-08-29T14:29:23.356177+00:00 app[web.1]: #1 /app/owa_coreAPI.php(830): owa_coreAPI::moduleFactory()
2021-08-29T14:29:23.356307+00:00 app[web.1]: #2 /app/owa_coreAPI.php(1350): owa_coreAPI::performAction()
2021-08-29T14:29:23.356439+00:00 app[web.1]: #3 /app/owa_caller.php(218): owa_coreAPI::handleRequest()
2021-08-29T14:29:23.356561+00:00 app[web.1]: #4 /app/owa_caller.php(160): owa_caller->handleRequest()
2021-08-29T14:29:23.356682+00:00 app[web.1]: #5 /app/index.php(45): owa_caller->handleRequestFromUrl()
2021-08-29T14:29:23.356708+00:00 app[web.1]: #6 {main}
2021-08-29T14:29:23.356795+00:00 app[web.1]:   thrown in /app/owa_lib.php on line 505
2021-08-29T14:29:23.357702+00:00 app[web.1]: 10.1.37.230 - - [29/Aug/2021:14:29:23 +0000] "GET /?

**Example**

**Comment by padams** [comment]
That is not the api endpoint. '''/api/''' is missing
