### ISSUE TITLE
Clicking the Funnel Visualization link under Goals in 1.7.2 displays

### ISSUE THREAD

**Issue by Mini2935** [Open-Web-Analytics/Open-Web-Analytics#788]
Clicking the Funnel Visualization link under Goals in 1.7.2 when page load nothing appear and when i see page in chrome i found it empty page!
!!??

**Comment by Mini2935** [comment]
in error log i found this line :

18:51:57 2021-11-09 5008 [debug_log] Object of class stdClass could not be converted to string

**Comment by wernight** [comment]
```
PHP Fatal error:  Uncaught Error: Object of class stdClass could not be converted to string in /var/www/html/modules/base/reportGoalFunnel.php:102
Stack trace:
#0 /var/www/html/owa_controller.php(302): owa_reportGoalFunnelController->action()
#1 /var/www/html/owa_coreAPI.php(881): owa_controller->doAction()
#2 /var/www/html/owa_coreAPI.php(868): owa_coreAPI::runController()
#3 /var/www/html/owa_coreAPI.php(1412): owa_coreAPI::performAction()
#4 /var/www/html/owa_caller.php(204): owa_coreAPI::handleRequest()
#5 /var/www/html/owa_caller.php(146): owa_caller->handleRequest()
#6 /var/www/html/index.php(45): owa_caller->handleRequestFromUrl()
#7 {main}
thrown in /var/www/html/modules/base/reportGoalFunnel.php on line 102, referer: https://example.com/index.php?owa_siteId=xxxxxxxxxxxxxxxxxxxxxxxx&owa_period=last_seven_days&owa_do=base.reportGoals
owa-0.owa.owa.svc.cluster.local:80 10.196.1.11 - - [08/Feb/2024:15:12:20 +0000] "GET /index.php?owa_siteId=xxxxxxxxxxxxxxxxxxxxxxxx&owa_period=last_seven_days&owa_do=base.reportGoalFunnel HTTP/1.1" 201 178 "https://example.com/index.php?owa_siteId=xxxxxxxxxxxxxxxxxxxxxxxx&owa_period=last_seven_days&owa_do=base.reportGoals" "Mozilla/5.0"
```
