### ISSUE TITLE
Reports data stuck à 0

### ISSUE THREAD

**Issue by vivetahiti** [Open-Web-Analytics/Open-Web-Analytics#816]
Before you open an issue:

    [ yep] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
    [ yep] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)
    [yep ] I have attached http headers, console/shell errors, or debug from OWA's error log file.
    `AddHandler application/x-httpd-php .tpl

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule api/(.*)$ api/index.php?owa_rest_params=$1 [QSA,NC,L]
Rewrites for new tracker location (../base/js/owa.tracker-combined-min.js) to new location (../bas>
need to properly sniff the protocol or else you could get a CSP error in the browser under https

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.tracker-combined-min.js$
RewriteCond %{HTTP:X-Forwarded-Proto} =https [OR]
RewriteCond %{HTTPS} =on [OR]
RewriteCond %{REQUEST_SCHEME} =https
RewriteRule owa.tracker-combined-min.js$ https://%{HTTP_HOST}%1/modules/base/dist/owa.tracker.js [NC>

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.(heatmap|vendors|player).js$
RewriteCond %{HTTP:X-Forwarded-Proto} =https [OR]
RewriteCond %{HTTPS} =on [OR]
RewriteCond %{REQUEST_SCHEME} =https
RewriteRule js$ https://%{HTTP_HOST}%1/modules/base/dist/owa.%2.js [NC,R=301,L]

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.tracker-combined-min.js$
RewriteCond %{HTTP:X-Forwarded-Proto} =http [OR]
RewriteCond %{HTTPS} =off [OR]
RewriteCond %{REQUEST_SCHEME} =http
RewriteRule owa.tracker-combined-min.js$ http://%{HTTP_HOST}%1/modules/base/dist/owa.tracker.js [NC,>

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.(heatmap|vendors|player).js$
RewriteCond %{HTTP:X-Forwarded-Proto} =http [OR]
RewriteCond %{HTTPS} =off [OR]
RewriteCond %{REQUEST_SCHEME} =http
RewriteRule js$ https://%{HTTP_HOST}%1/modules/base/dist/owa.%2.js [NC,R=301,L]
` [yep] I have attached my /var/log/apache2/error.log for this website : `sudo cat /var/log/apache2/error.stats.log [Thu Feb 10 21:02:24.477969 2022] [php7:error] [pid 417172] [client 141.101.68.173:46736] PHP Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/www/html/stats/owa-data/logs/errors_d41d8cd98f00b204e9800998ecf8427e.txt" could not be opened in append mode: failed to open stream: Permission denied in /var/www/html/stats/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146\nStack trace:\n#0 /var/www/html/stats/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\\Handler\\StreamHandler->write()\n#1 /var/www/html/stats/vendor/monolog/monolog/src/Monolog/Logger.php(327): Monolog\\Handler\\AbstractProcessingHandler->handle()\n#2 /var/www/html/stats/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\\Logger->addRecord()\n#3 /var/www/html/stats/modules/base/classes/error.php(222): Monolog\\Logger->error()\n#4 /var/www/html/stats/modules/base/classes/error.php(181): owa_error->logMsg()\n#5 /var/www/html/stats/modules/base/classes/error.php(254): owa_error->log()\n#6 /var/www/html/stats/modules/base/classes/error.php(104): owa_error->logBufferedMsgs()\n#7 /var/www/ in /var/www/html/stats/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 146 [Thu Feb 10 21:03:19.140714 2022] [php7:notice] [pid 417175] [client 141.101.69.168:47166] PHP Notice: Undefined variable: page_title in /var/www/html/stats/modules/base/templates/wrapper_default.tpl on line 6 [Thu Feb 10 21:03:21.004031 2022] [php7:notice] [pid 417172] [client 141.101.69.168:47414] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_config_entry.php on line 33, referer: https://stats.secu.host/install.php [Thu Feb 10 21:03:21.004077 2022] [php7:notice] [pid 417172] [client 141.101.69.168:47414] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_config_entry.php on line 41, referer: https://stats.secu.host/install.php [Thu Feb 10 21:03:21.004092 2022] [php7:notice] [pid 417172] [client 141.101.69.168:47414] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_config_entry.php on line 49, referer: https://stats.secu.host/install.php [Thu Feb 10 21:03:21.004103 2022] [php7:notice] [pid 417172] [client 141.101.69.168:47414] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_config_entry.php on line 57, referer: https://stats.secu.host/install.php [Thu Feb 10 21:03:21.004111 2022] [php7:notice] [pid 417172] [client 141.101.69.168:47414] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_config_entry.php on line 65, referer: https://stats.secu.host/install.php [Thu Feb 10 21:04:23.757645 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_DB_TYPE already defined in /var/www/html/stats/owa-config.php on line 38, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.757701 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_DB_NAME already defined in /var/www/html/stats/owa-config.php on line 39, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.757710 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_DB_HOST already defined in /var/www/html/stats/owa-config.php on line 40, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.757717 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_DB_USER already defined in /var/www/html/stats/owa-config.php on line 41, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.757724 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_DB_PORT already defined in /var/www/html/stats/owa-config.php on line 42, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.757742 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_DB_PASSWORD already defined in /var/www/html/stats/owa-config.php on line 43, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.757751 2022] [php7:notice] [pid 417171] [client 141.101.68.115:58956] PHP Notice: Constant OWA_PUBLIC_URL already defined in /var/www/html/stats/owa-config.php on line 62, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.845357 2022] [php7:notice] [pid 417175] [client 141.101.68.115:59326] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.852960 2022] [php7:notice] [pid 417175] [client 141.101.68.115:59326] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_defaults_entry.php on line 12, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.852991 2022] [php7:notice] [pid 417175] [client 141.101.68.115:59326] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_defaults_entry.php on line 20, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:23.852999 2022] [php7:notice] [pid 417175] [client 141.101.68.115:59326] PHP Notice: Trying to access array offset on value of type bool in /var/www/html/stats/modules/base/templates/install_defaults_entry.php on line 28, referer: https://stats.secu.host/install.php?owa_action=base.installCheckEnv [Thu Feb 10 21:04:56.283297 2022] [php7:notice] [pid 417190] [client 141.101.68.165:52568] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/install.php?owa_do=base.installDefaultsEntry&owa_site_id=& [Thu Feb 10 21:04:56.660104 2022] [php7:notice] [pid 417190] [client 141.101.68.165:52568] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/install.php?owa_do=base.installDefaultsEntry&owa_site_id=& [Thu Feb 10 21:04:56.660820 2022] [php7:notice] [pid 417190] [client 141.101.68.165:52568] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/install.php?owa_do=base.installDefaultsEntry&owa_site_id=& [Thu Feb 10 21:04:56.762008 2022] [php7:notice] [pid 417190] [client 141.101.68.165:52568] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/install.php?owa_do=base.installDefaultsEntry&owa_site_id=& [Thu Feb 10 21:04:56.764601 2022] [php7:notice] [pid 417190] [client 141.101.68.165:52568] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/install.php?owa_do=base.installDefaultsEntry&owa_site_id=& [Thu Feb 10 21:05:39.873322 2022] [php7:notice] [pid 417171] [client 141.101.68.165:52732] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:05:39.874074 2022] [php7:notice] [pid 417171] [client 141.101.68.165:52732] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:05:39.878734 2022] [php7:notice] [pid 417171] [client 141.101.68.165:52732] PHP Notice: Array to string conversion in /var/www/html/stats/owa_lib.php on line 725, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:13.493886 2022] [php7:notice] [pid 417206] [client 141.101.68.165:24508] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:13.494215 2022] [php7:notice] [pid 417206] [client 141.101.68.165:24508] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:13.495525 2022] [php7:notice] [pid 417206] [client 141.101.68.165:24508] PHP Notice: Array to string conversion in /var/www/html/stats/owa_lib.php on line 725, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:31.237496 2022] [php7:notice] [pid 417206] [client 141.101.68.165:28438] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:31.237771 2022] [php7:notice] [pid 417206] [client 141.101.68.165:28438] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:31.239889 2022] [php7:notice] [pid 417206] [client 141.101.68.165:28438] PHP Notice: Array to string conversion in /var/www/html/stats/owa_lib.php on line 725, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:46.148086 2022] [php7:notice] [pid 417215] [client 141.101.68.165:20910] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:46.148381 2022] [php7:notice] [pid 417215] [client 141.101.68.165:20910] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:46.152053 2022] [php7:notice] [pid 417215] [client 141.101.68.165:20910] PHP Notice: Array to string conversion in /var/www/html/stats/owa_lib.php on line 725, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:06:56.334243 2022] [php7:notice] [pid 417277] [client 141.101.68.165:41912] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:07:06.180938 2022] [php7:notice] [pid 417227] [client 141.101.68.165:61314] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:07:06.181230 2022] [php7:notice] [pid 417227] [client 141.101.68.165:61314] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:07:06.184322 2022] [php7:notice] [pid 417227] [client 141.101.68.165:61314] PHP Notice: Array to string conversion in /var/www/html/stats/owa_lib.php on line 725, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:07:27.909091 2022] [php7:notice] [pid 417252] [client 141.101.68.165:51882] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:07:27.909441 2022] [php7:notice] [pid 417252] [client 141.101.68.165:51882] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:07:27.911186 2022] [php7:notice] [pid 417252] [client 141.101.68.165:51882] PHP Notice: Array to string conversion in /var/www/html/stats/owa_lib.php on line 725, referer: https://stats.secu.host/index.php?owa_do=base.sitesProfile [Thu Feb 10 21:11:17.831552 2022] [php7:notice] [pid 417227] [client 172.70.242.151:54668] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:12:06.297019 2022] [php7:notice] [pid 417222] [client 172.70.242.123:23378] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:12:45.108524 2022] [php7:notice] [pid 417280] [client 172.70.246.147:34764] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:13:00.323361 2022] [php7:notice] [pid 417222] [client 162.158.91.134:53920] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:18:07.499589 2022] [php7:notice] [pid 417384] [client 172.70.250.191:18192] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:18:19.763149 2022] [php7:notice] [pid 417350] [client 172.70.242.201:38676] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:18:24.421731 2022] [php7:notice] [pid 417222] [client 172.70.250.191:48996] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:18:30.737389 2022] [php7:notice] [pid 417388] [client 162.158.91.14:29844] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:20:07.244756 2022] [php7:notice] [pid 417417] [client 172.70.242.123:53224] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:20:28.662652 2022] [php7:notice] [pid 417387] [client 172.70.242.151:25958] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 356 [Thu Feb 10 21:59:24.270403 2022] [php7:notice] [pid 418084] [client 162.158.91.130:9506] PHP Notice: Trying to access array offset on value of type null in /var/www/html/stats/owa_db.php on line 35`

OWA Version: 1.7.5

PHP Version: 7.4.3 with no fpm

Webserver: Apache

Browser: Firefox 96

Description
all websites reports are stuck at 0
i made a clean and complete installation of the plugin on Word Press 5.9

How to reproduce
I deployed OWA on a fresh VPS: no problem
I installed Word Press official Plugin: no problem
I configured the plugin correctly, with my OWA server php config data: connected
I chose a website ID within the provided list of the plugin config page: ok
I cliked on the Word Press OWA link "OWA/Analytics/Launch your OWA Dashboard and landed on my OWA distant server : ok
I went to Site Roster, then chose my website, and clicked View Reports : all is at 0
I did it for 7 websites, all reports data is at 0

I tried Tracking code (javascript) in a footer of a website, did not work neither. Is it required anyway after doing all that ?
Sorry I did not know how to re-open.

Possible Solution

Additional context

**Comment by padams** [comment]
Well that PHP fatal doesn't look good. likely a permissions issue.
