### ISSUE TITLE
Error from debuging

### ISSUE THREAD

**Issue by pietru2004** [Open-Web-Analytics/Open-Web-Analytics#818]
I have found an error while debugging OWA (I was not getting any data), is the error from below disappearing my data ?

`
[12:53:30 2022-02-15] [21339] [DEBUG] Filter: owa_trackingEventHelpers::setRepeatVisitorFlag. Value passed:   
[12:53:30 2022-02-15] [21339] [DEBUG] Filter: owa_trackingEventHelpers::setRepeatVisitorFlag. Value returned: 1  
[12:53:30 2022-02-15] [21339] [DEBUG] is_repeat_visitor filtered by owa_trackingEventHelpers::setRepeatVisitorFlag.  
[12:53:30 2022-02-15] [21339] [DEBUG] Filtering full_host  
[12:53:30 2022-02-15] [21339] [DEBUG] Filter: owa_trackingEventHelpers::resolveFullHost. Value passed:   
[12:53:30 2022-02-15] [21339] [NOTICE] filter_var() expects at most 3 arguments, 4 given // #0 path/AnaliticsP/modules/base/classes/trackingEventHelpers.php(833): filter_var()
#1 path/AnaliticsP/modules/base/classes/eventDispatch.php(249): owa_trackingEventHelpers::resolveFullHost()
#2 path/AnaliticsP/modules/base/classes/trackingEventHelpers.php(133): owa_eventDispatch->filter()
#3 path/AnaliticsP/modules/base/processEvent.php(108): owa_trackingEventHelpers->setTrackerProperties()
#4 path/AnaliticsP/owa_controller.php(278): owa_processEventController->pre()
#5 path/AnaliticsP/owa_coreAPI.php(880): owa_controller->doAction()
#6 path/AnaliticsP/owa_coreAPI.php(867): owa_coreAPI::runController()
#7 path/AnaliticsP/owa_coreAPI.php(999): owa_coreAPI::performAction()
#8 path/AnaliticsP/log.php(101): owa_coreAPI::logEvent()
#9 {main}  
[12:53:30 2022-02-15] [21339] [DEBUG] Total session time: 0.061115980148315  
[12:53:30 2022-02-15] [21339] [DEBUG] Goodbye from OWA  
[12:53:30 2022-02-15] [21339] [DEBUG] starting to persist cache...  
[12:53:30 2022-02-15] [21339] [DEBUG] There is no cold cache to persist to.  
[12:53:30 2022-02-15] [21339] [DEBUG] Cache Statistics: 
                          Total Hits: 1 (Warm/Cold: 1/0)
                          Total Miss: 3
                          Total Added to Cache: 2
                          Total Replaced: 0
                          Total Dirty: 2
                          Total Persisted: 0
                          Total Removed: 0  
`

**Comment by pietru2004** [comment]
erm if I were to copy those fixes into php files on my srv would OWA work? (or should I wait for next release ?)

**Comment by padams** [comment]
I'm going to push a release shortly.

**Comment by pietru2004** [comment]
ok, thank you
