### ISSUE TITLE
Bug on API under ubuntu 20.04?

### ISSUE THREAD

**Issue by c-orazio** [Open-Web-Analytics/Open-Web-Analytics#856]
**OWA Version**: 1.7.7

**PHP Version**: 7.4

**Webserver**: Apache

**Description**  
OWA seems to work properly, but I found this in the log : 
 Uncaught Error: Class 'owa_db_' not found in /var/www/owa/owa_coreAPI.php:115\nStack trace:\n#0 /var/www/owa/owa_coreAPI.php(99): owa_coreAPI::dbFactory()\n#1 /var/www/owa/owa_entity.php(472): owa_coreAPI::dbSingleton()\n#2 /var/www/owa/owa_auth.php(408): owa_entity->getByColumn()\n#3 /var/www/owa/owa_auth.php(422): owa_auth->getUser()\n#4 /var/www/owa/owa_auth.php(221): owa_auth->isUser()\n#5 /var/www/owa/owa_auth.php(135): owa_auth->authByCookies()\n#6 /var/www/owa/owa_controller.php(326): owa_auth->authenticateUser()\n#7 /var/www/owa/owa_controller.php(220): owa_controller->checkCapabilityAndAuthenticateUser()\n#8 /var/www/owa/owa_coreAPI.php(880): owa_controller->doAction()\n#9 /var/www/owa/owa_coreAPI.php(867): owa_coreAPI::runController()\n#10 /var/www/owa/owa_coreAPI.php(1411): owa_coreAPI::performAction()\n#11 /var/www/owa/owa_caller.php(204): owa_coreAPI::handleRequest()\n#12 /var/www/owa/install.php(52): owa_caller->handleRequest()\n#13 {main}\n  thrown in /var/www/owa/owa_coreAPI.php on line 115

**Comment by c-orazio** [comment]
seems to work with SPIP
