### ISSUE TITLE
PHP fatal error on install.

### ISSUE THREAD

**Issue by ManySolutions** [Open-Web-Analytics/Open-Web-Analytics#884]
- [ ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide

**Affected Version(s)**: 1.7.8

**PHP Version**: 8.0.28 FPM

**Webserver**: Apache

**Installation Type**

- [ ] Standalone

**Description**  
Followed the instructions to extract the files to the httpdocs folder and went to /install.php as instructed. I get 
"This page isn’t owa.co.uk is currently unable to handle this request.
HTTP ERROR 500"
When I check the server logs I see the error:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class "Monolog\\Logger" not found in /var/www/vhosts/owa.co.uk/httpdocs/modules/base/classes/error.php:68\nStack trace:\n#0 /var/www/vhosts/owa.co.uk/httpdocs/owa_lib.php(489): owa_error->__construct()\n#1 /var/www/vhosts/owa.co.uk/httpdocs/owa_coreAPI.php(487): owa_lib::factory()\n#2 /var/www/vhosts/owa.co.uk/httpdocs/owa_coreAPI.php(158): owa_coreAPI::supportClassFactory()\n#3 /var/www/vhosts/owa.co.uk/httpdocs/owa_base.php(77): owa_coreAPI::errorSingleton()\n#4 /var/www/vhosts/owa.co.uk/httpdocs/owa_caller.php(76): owa_base->__construct()\n#5 /var/www/vhosts/owa.co.uk/httpdocs/owa.php(24): owa_caller->__construct()\n#6 /var/www/vhosts/owa.co.uk/httpdocs/install.php(38): owa->__construct()\n#7 {main}\n thrown in /var/www/vhosts/owa.co.uk/httpdocs/modules/base/classes/error.php on line 68'

**Additional context**  
I am using plesk as my control panel to upload the files. I have also tried changing the file permissions to 777 just so i am 100% that is not the issue.

**Comment by thiblcr** [comment]
Same error with php8.1 on RockyLinux 9.1

**Comment by tcreek** [comment]
Does not work with PHP 8. CLose this
