### ISSUE TITLE
Installation errror 

### ISSUE THREAD

**Issue by pvalen** [Open-Web-Analytics/Open-Web-Analytics#919]
Version 1.7.8

PHP 8.24
Webserver: Apache
Browser: Firefox, Chrome, Edge
Installation unzip from owa_1.7.8_packaged.tar

I'm testing it locally, on Xampp.
I extracted the package to the appropriate directory.
Ran the installation and it reported the errors below:

```
Deprecated: Optional parameter $name declared before required parameter $value is implicitly treated as a required parameter in D:\xampp824\htdocs\owa\owa_coreAPI.php on line 1233

Deprecated: Creation of dynamic property owa_error::$logger is deprecated in D:\xampp824\htdocs\owa\modules\base\classes\error.php on line 68

Fatal error: Uncaught Error: Undefined constant "OWA_DTD_BIGINT" in D:\xampp824\htdocs\owa\modules\base\entities\configuration.php:37 Stack trace: #0 D:\xampp824\htdocs\owa\owa_lib.php(489): owa_configuration->__construct('') #1 D:\xampp824\htdocs\owa\owa_coreAPI.php(561): owa_lib::factory('D:\\xampp824\\htd...', '', 'owa_configurati...', '') #2 D:\xampp824\htdocs\owa\owa_coreAPI.php(521): owa_coreAPI::moduleSpecificFactory('base.configurat...', 'entities', '', '', false) #3 D:\xampp824\htdocs\owa\modules\base\classes\settings.php(72): owa_coreAPI::entityFactory('base.configurat...') #4 D:\xampp824\htdocs\owa\owa_lib.php(489): owa_settings->__construct(Array) #5 D:\xampp824\htdocs\owa\owa_coreAPI.php(487): owa_lib::factory('D:\\xampp824\\htd...', 'owa_', 'settings', Array) #6 D:\xampp824\htdocs\owa\owa_coreAPI.php(142): owa_coreAPI::supportClassFactory('base', 'settings') #7 D:\xampp824\htdocs\owa\owa_base.php(78): owa_coreAPI::configSingleton() #8 D:\xampp824\htdocs\owa\owa_caller.php(76): owa_base->__construct() #9 D:\xampp824\htdocs\owa\owa.php(24): owa_caller->__construct(NULL) #10 D:\xampp824\htdocs\owa\install.php(64): owa->__construct() #11 {main} thrown in D:\xampp824\htdocs\owa\modules\base\entities\configuration.php on line 37
```

Petr

**Comment by clintguy74** [comment]
Likewise I am also getting lots of errors. there is very little information if OWA, is PHP 8 compatible? 

 PHP Fatal error:  Uncaught Error: Undefined constant "OWA_DTD_BIGINT" in /var/www/html/owa/modules/base/entities/configuration.php:37
Stack trace:
 /var/www/html/owa/owa_lib.php(489): owa_configuration->__construct()\n#1
/var/www/html/owa/owa_coreAPI.php(561): owa_lib::factory()\n#2 
/var/www/html/owa/owa_coreAPI.php(521): owa_coreAPI::moduleSpecificFactory()
/var/www/html/owa/modules/base/classes/settings.php(72): owa_coreAPI::entityFactory()
 /var/www/html/owa/owa_lib.php(489): owa_settings->__construct()
 /var/www/html/owa/owa_coreAPI.php(487): owa_lib::factory()
 /var/www/html/owa/owa_coreAPI.php(142): owa_coreAPI::supportClassFactory()
 /var/www/html/owa/owa_base.php(78): owa_coreAPI::configSingleton()
 /var/www/html/owa/owa_caller.php(76): owa_base->__construct()
 /var/www/html/owa/owa.php(24): owa_caller->__construct()
 /var/www/html/owa/install.php(38): owa->__construct()
 {main}\n  thrown in /var/www/html/owa/modules/base/entities/configuration.php on line 37

**Comment by pvalen** [comment]
Yes, as I later found out, they do not support PHP 8.
Take a look here
https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/893
And it looks like it won't be supported that fast either ;-(

**Comment by clintguy74** [comment]
Its such a pity,  I always make sure that when I use software I support the developers with donations, but when they not interested, then but to look other places and support developers that want to be supported
