### ISSUE TITLE
Why does it not install right anymore? Tried on all versions of php

### ISSUE THREAD

**Issue by JoshWho** [Open-Web-Analytics/Open-Web-Analytics#925]
I can't get a fresh install to work no matter what php I use. fresh upload right off the bat starts with a 500 error on the home page

![Screenshot (2)](https://github.com/user-attachments/assets/0dce9f0e-0237-4083-9dbf-4a994588d72c)

Tried php 7.2 all the way up to 8.1 they all do this 500 error

**Comment by JoshWho** [comment]
I used this a year ago and it use to be flawless to install. What changed?

**Comment by DynWeb-John** [comment]
I just tried to install the OWA today and got the same issue.
I did a view of the error log and got the following:
[18-Sep-2024 14:36:58 XXXX] PHP Fatal error:  Uncaught Error: Class "Monolog\Logger" not found in /home/XXXX/owa.XXXX.com.au/Open-Web-Analytics-master/modules/base/classes/error.php:68
Stack trace:
#0 /home/XXXX/XXXX/Open-Web-Analytics-master/owa_lib.php(489): owa_error->__construct()
#1 /home/XXXX/XXXX/Open-Web-Analytics-master/owa_coreAPI.php(487): owa_lib::factory()
#2 /home/XXXX/XXXX/Open-Web-Analytics-master/owa_coreAPI.php(158): owa_coreAPI::supportClassFactory()
#3 /home/XXXX/XXXX/Open-Web-Analytics-master/owa_base.php(77): owa_coreAPI::errorSingleton()
#4 /home/XXXX/XXXX/Open-Web-Analytics-master/owa_caller.php(76): owa_base->__construct()
#5 /home/XXXX/XXXX/Open-Web-Analytics-master/owa.php(24): owa_caller->__construct()
#6 /home/XXXX/XXXX/Open-Web-Analytics-master/install.php(38): owa->__construct()
#7 {main}
  thrown in /home/XXXX/XXXX/Open-Web-Analytics-master/modules/base/classes/error.php on line 68

It looks like the error is being caused because there is a new dependency on "Monolog" which isn't available by default and also isn't listed in the installation instructions for OWA.
This might help anyone investigating this issue further.

**Comment by akalsey** [comment]
Running "composer install" from the OWA directory resolved this for me. This installed the dependencies that weren't in the download.
